### ISSUE TITLE
Unable to start pumps 

### ISSUE THREAD

**Issue by zetaab** [ccutrer/balboa_worldwide_app#70]
<img width="468" alt="Screenshot 2023-02-11 at 8 36 32" src="https://user-images.githubusercontent.com/22482503/218244458-82eba3c2-08ff-44fe-8754-8ac9851e0c3c.png">

when I am clicking "hot tub pumps" in UI I will get following error and the app will crash

```
/usr/local/bundle/gems/balboa_worldwide_app-2.1.3/lib/bwa/client.rb:173:in `set_pump': undefined method `zero?' for true:TrueClass (NoMethodError)

      return toggle_item(:soak) if desired.zero? && configuration.pumps.length == 1 && max_pump_speed != 1
                                          ^^^^^^
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/exe/bwa_mqtt_bridge:292:in `block (3 levels) in publish_basic_attributes'
	from /usr/local/bundle/gems/homie-mqtt-1.6.3/lib/mqtt/homie/property.rb:175:in `set'
	from /usr/local/bundle/gems/homie-mqtt-1.6.3/lib/mqtt/homie/device.rb:118:in `block (3 levels) in publish'
	from /usr/local/bundle/gems/mqtt-ccutrer-1.0.3/lib/mqtt/client.rb:468:in `block in get'
	from /usr/local/bundle/gems/mqtt-ccutrer-1.0.3/lib/mqtt/client.rb:454:in `loop'
	from /usr/local/bundle/gems/mqtt-ccutrer-1.0.3/lib/mqtt/client.rb:454:in `get'
	from /usr/local/bundle/gems/homie-mqtt-1.6.3/lib/mqtt/homie/device.rb:107:in `block (2 levels) in publish'
/usr/local/bundle/gems/balboa_worldwide_app-2.1.3/lib/bwa/client.rb:72:in `readpartial': end of file reached (EOFError)
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/lib/bwa/client.rb:72:in `block in poll'
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/lib/bwa/client.rb:62:in `loop'
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/lib/bwa/client.rb:62:in `poll'
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/exe/bwa_mqtt_bridge:59:in `block in initialize'
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/exe/bwa_mqtt_bridge:58:in `loop'
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/exe/bwa_mqtt_bridge:58:in `initialize'
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/exe/bwa_mqtt_bridge:418:in `new'
	from /usr/local/bundle/gems/balboa_worldwide_app-2.1.3/exe/bwa_mqtt_bridge:418:in `<top (required)>'
	from /usr/local/bundle/bin/bwa_mqtt_bridge:25:in `load'
	from /usr/local/bundle/bin/bwa_mqtt_bridge:25:in `<main>'
```

The state of pumps are updating fine. If I start them manually from hot tub it will update the state to home assistant UI, but modifying the state from HA is not working.

**Comment by Danm-89** [comment]
I am having the same issue as above. The device goes offline in HA when I try and toggle the pumps, but if I use the control panel on the tub they toggle in HA.
